var paragraphs = [
  "(1) I hold vivid memories of our college conducting classes online during our first semester. Little did I know when I sent you that very first message, that you would become such an indispensable part of my life. Our initial conversation revolved around introductions, asking about each other, our whereabouts, and even suggesting that you could join us for a meet-up. Back then, my impression of you was casual, not paying meticulous attention to every detail. But now, as I pen down these words, our relationship has flourished over the past six months, and our journey together feels like a captivating movie. I recollect the times when my college friends and I made plans to visit the campus, and I would occasionally ask if we should meet there, considering the online nature of our classes. However, you would decline, embracing your introverted nature 😂.",
  "(2) After that, our second semester in colleges started offline.I have a best friend Aarushi, and you have Darshita as your best friend. I have a good bond with Darshita, but not with you. When we shot a video in the English group, I came to know that you had a negative experience with me, and you felt that I only give importance to Darshita and focus solely on my own interests.At that time, I didn't have any such intentions, but if you felt bad, then I apologize.",
  "(3) our journey received a spark from a friendship where you began to know me a little during the time of Navratri.but still At that time, I appeared to be the most irritating person to you.To be honest, I didn't have a full-blown crush or anything on you during that Navratri period. It was more of a kind of attraction where I enjoyed being around you, and it felt like I'd rather be with you than my friends.going with you to get a water bottle, making sure you were covered from the crowd, being careful not to step on your chaniyacholi, walking attentively behind you, being only with you, dancing Garba with you - all of these things gave me a great feeling.I remember when you lost your earrings on the last day of Navratri, and despite knowing that you may not be aware of it, even after you left, I was searching for those earrings. I also recall jokingly mentioning that I would get you new ones on your birthday, but you responded rudely, saying it wasn't necessary.Your rude behavior and your avoidance seemed normal to me in that jolly mood of mine, and I understood that if it were any other girl, she might have reacted the same way. Being rude doesn't make you a mean person.",
  "(4) After Navratri, I came to realize that I enjoyed your company and simply cherished your presence. I longed for a genuine friendship, even though it was still in its nascent stages.that's why whenever I had free time or felt inclined, I derived pleasure from being in your company. It became a routine for me to sit with you during Mala ma'am's lectures. Initially, it wasn't a deliberate choice, but over time, sitting together started bringing me joy, and I willingly continued doing so. I guess there was a time when you found me the most irritating, and I suppose you went home and told your mother everything about me.",
  "(5) I remember the day when Darshita said, Yar, his mom radiates such positive vibes, and I told you about it, saying, I wish Kashish could take me to your home, I also want to experience the positive energy by meeting your mom. At that time, you responded in a rather rude manner, saying that my life, my mom, and my family are private to me and reserved only for a few select people.Not every day, but sometimes in college, it felt like you were seeing me everywhere you looked. Whether it was during our arrivals or departures, I would purposely pass by you. 😂 I tried these tactics in the hope that you would notice me or we would cross paths.",
  "(6) gradually, you started realizing that the more irritating I was, the more lovable I became.I remember that gradually, every day I would search for something new to talk to you about. Maybe my interest in you was growing. One day, I remember showing you my childhood photos, and your reaction was like, Yarrrr, these photos are so cute! That day, I felt happy knowing that I was adorable as a child, and it made me realize how different I look now. From that moment, I started paying more attention to improving my dressing sense and taking care of my body. Of course, I used to care about my appearance before, but I hadn't learned how to manage it properly. You gave me the motivation to take better care of myself.",
  "(7) In the given timeframe, I remember a few conversations, and if I want to share there was one where I mustered up the courage to ask you if you had a boyfriend because I thought you might be more comfortable discussing such matters. However, you declined and mentioned that you weren't interested in those things, and you also mentioned that people at home have access to my phone. Therefore, you suggested keeping all such conversations face-to-face, even though we hardly ever spoke face-to-face during that time. It meant that you were not interested in talking about anything, and That's when the boundaries were set, limited to just friendship.",
  "(8) Yes, I remember those chat conversations when we had our first actual conflict, where we were on opposite sides. I had asked you about how I truly am and to tell me the worst things about me because I used to ask this question to my close ones to learn from my mistakes to avoid hurting those who are important to me. At that time, you responded with such rudeness, saying that I shouldn't seek validation from others, and you advised me not to be a people-pleaser, among other things. However, that conversation ended with me saying not to worry because I would prove it to you someday, if not today, and in the near future, I have indeed shown you that several times, haven't I, Kishu?",
  "(9) Our journey, full of unexpected twists and turns, led us to the beginning of a genuine friendship during our second-semester exams. You surely remember that days. It was during Mala ma'am's final practicals for OOPC when I taught you the *copy constructor* concept late into the night. To our surprise, that very topic appeared in the exam. You later told me about the immense happiness you felt that day, although I couldn't see it from your poker face. Your response remained calm and straightforward, just mentioning that the exam went well.huh, poker face champion! ",
  "(10) I cherished the desire to meet you after every exam, eagerly waiting for you and strolling around the area where you would head towards the parking lot after completing your exams. I distinctly recall the day of our last exam in semester two when I waited for you for an hour and a half. To my surprise, I later discovered that you had already reached home after finishing your exams.(That particular day was December 18, 2022) On that very day, I dialed your number and enthusiastically invited you to the upcoming cultural festival in our college. Despite your prior refusals, I assured you that there was no need to worry and requested you to at least join on the first day. I promised to accompany you throughout the day, ensuring that you never felt alone. My only wish was for you to be a part of the culfest, and I was determined to make it happen, regardless of the circumstances.",
  "(11) On December 21st, our actual journey began, paving the way for a series of special moments between us. This pivotal moment marked a turning point as our friendship started to thrive, and we grew more comfortable with each other. During these 3 days, we consciously embraced kindness and consideration in our interactions, deepening our connection. I apologize to my friends, but I must admit that being with you brought me the utmost happiness. Throughout the entire culfest, my heart and mind were solely focused on being in your presence. We had a great time together, meaning a lot of fun was had.",
  "(12) During those three days, we experienced an incredible amount of joy. We would rise early in the morning, swiftly prepare ourselves, and eagerly make our way to college. The culfest's diverse lineup of programs and events brought us immense delight. In the afternoon, we would briefly return home to grab a bite to eat and swiftly change into new, fashionable attire. Each day had its unique dress code, and we relished the opportunity to dress up accordingly. As evening descended, or even late into the night, we would wearily return home, yet our hearts were filled with contentment, cherishing the profound happiness those days bestowed upon us. Truly, those days were etched in our memories as unforgettable moments.",
  "(13) On that memorable night of December 23rd, when you left earlier, I experienced the profound feeling of missing you for the first time. It was a poignant realization that you had become an integral part of my life, and your absence, as you left earlier on the last day of culfest, made me acutely aware of the depth of our connection.Furthermore, I vividly recall our very first and longest chat conversation, which took place on that special night. As we exchanged messages, the excitement and joy were palpable, and I could feel the exhilaration coursing through my veins. It was an indelible experience that left me filled with anticipation and a sense of excitement that I will cherish forever.",
  "(14) The end of our second semester and the year 2022 came with an exhilarating and thrilling feeling. During college, we had a Christmas break. On the memorable night of December 31st, we had planned to attend a party, but regrettably, you were unable to join us due to family obligations.I remember that night very well. Even after a week of culfest, the hangover was still lingering, and along with it, thoughts of you occupied my mind. I missed you the most at the party, which is why I left home before midnight so I could message you and be the first to wish you a happy new year in 2023. Talking to you every night had become a habit, It was so enjoyable for both of us to connect with each other at night. Despite deciding at times not to chat late into the night, we never actually followed through with it. That was the time when we began developing feelings for each other. Do you remember, Kashish Jain?",
  "(15) In the early days of January 2023, as the year unfolded its chapters, our love story began to write its first lines. It was during the magical first week of the month that our hearts intertwined, weaving a tapestry of affection and hope. As the world embraced the new year, we embarked on a journey of love, destined to shape the chapters of our lives.That night and our conversation, I still remember them. You told me that you have 1% feeling for me, that you like me 1%. I was very happy to hear that because, despite all my efforts, even if they were limited to just friendship, I was willing to accept it. But that confession gave a glimmer of hope to the desire in my heart. As Always i tried to made you feel very normal and comfortable that day because I wanted to listen to your emotions with patience and understanding.",
  "(16) The confession brought with it a sense of fear, a fear intertwined with concerns about the future and the acceptance of our families. On that day, she reminded me once again of her Jain background and the fact that her family only allows Jain marriages. Although our connection was initially just a mere 1% of liking, there was something profound beyond that small percentage.Just as I was ready for friendship, I have always been willing to adapt and manage things according to your comfort. I don't know why or how those efforts were coming from me, but I was constantly motivated to make them, just because of you. During that time, the actual initiation of our love story has unfolded, and those days are filled with pure joy. Each day brings a renewed eagerness to attend college, a source of happiness upon waking up, a determination to maintain a positive outlook, and an extra effort to prepare ourselves for the day ahead. Bro, it's just 1%, but it feels like so much more.",
  "(17) At that time, we were completely unaware, but we knew deep down that there was something between us. However, it was not fully accepted. Naturally, conflicts arise due to a lack of acceptance, and during that time, we faced and felt numerous conflicts. Those conflicts were significant, and it's remarkable that we have been able to face them so well. It seems like it has always been our strength to confront those conflicts in a positive and effective manner. Hopefully, we will continue to do so in the future as well.During that period, the circumstances were teetering on the edge, creating a sense of unease. It felt as though anything could happen if we didn't exercise patience. Amidst the uncertainties, I found myself gripped with fear—a fear rooted in the possibility of losing you",
  "(18) I remember those conversations when you expressed your concerns about accepting me and the uncertainty of our parents' approval. You always prioritized honesty and didn't want to hurt anyone. I recall my response where I mentioned that whatever I was giving you in terms of affection and care, it was not based on any expectations. I genuinely felt for you and wanted to continue our connection, regardless of what the future held. You asked what would happen if I couldn't reciprocate those feelings, and I reassured you that my feelings for you would persist even if you didn't feel the same way.I'm grateful to god for granting me the strength and patience to endure and navigate through challenging times. It is through that resilience that our bond has grown stronger and more resilient as well.",
  "(19) I remember when you shared with me that we had to put a stop to everything because it was too risky. Despite the uncertainty and the slim chance of success, we chose to hold onto that less than 1% possibility of being together. We couldn't predict what the future held for us, but we both knew deep down that we wanted each other, no matter the cost.On that very day, I couldn't bear the pain of stopping myself from liking you. you told me,don't let it consume you.when Selvi mam gave a lecture in LR1 and the A and B batches were merged.On that day, I felt a great deal of pain, as I didn't want to lose you. I was overwhelmed by a deep fear that I had never experienced before in my life.After spending so much time together, that day it was the first time I intentionally touched you.",
  "(20) After the confession, I had a strong desire during every lecture, whenever I sat next to you, to hold your pinky finger with mine. However, I was never successful in doing so because I was too scared that you would feel offended or upset. But on that particular day, I couldn't control myself anymore. I couldn't stop myself from liking you, and for me, it was more than just a simple liking. It was a profound feeling that went beyond mere attraction.After holding your finger, the feeling I experienced was beyond words. My heart was racing at the speed of light, and my emotions and hormones were heightened. It was an intense and exhilarating sensation that overwhelmed me completely.I stopped feeling scared and found great comfort being around you.you should not have held my finger, but you did it nonetheless. you started developing stronger feelings for me during that phase of our lives. Although it may not have been appropriate for you to hold my finger, you couldn't resist the urge and did it anyway.",
  "(21) During that phase of our lives that your feelings for me started to deepen and grow stronger.That was the very first special thing in our lives that was shared exclusively between the two of us. However, the fear of potential challenges and uncertainties still existed.I swear, ever since that moment, I had a small inkling in my mind that if I hold someone's hand in the future, it would be yours.That night, you told me that your liking for me had grown to 10%. Of course, the exact percentage doesn't matter, but it was still significant to acknowledge the growth of your feelings towards me.",
  "(22) Uttarayan is one of my favorite festivals, but I couldn't celebrate it due to my cousin's wedding. It was just the beginning of our connection, but even during that time, you used to share your photos with me from time to time so that I wouldn't feel alone. Your Instagram reels with me being present or referenced in them were so lovely, and I have adored them from then until now. Sending me your photos and videos, oh my, it felt so special. You started this wonderful gesture of keeping me updated through photos and videos, and it has never been like a binding relationship between us. But I truly love this type of love, where we share photos and videos. By sharing them, we also felt included and loved always.",
  "(23) Everything was going fine at that time, and then you confessed something to me. You had a boyfriend, and your mother had found out about him. you started to feel the same fear of losing me at that time, and I just became frightened again. During that time, both of us were completely confused. We had numerous questions in our minds, but thanks to Darshita and Aarushi, we navigated through that phase. We decided to enjoy our feelings and stay together until it felt like we were ready for marriage. Until then, why spoil the enjoyment of this phase of life? However, it was just a satisfaction reason to stay together because love had already started to blossom.But until today, neither of us has proposed to each other because we are not yet ready, not yet worthy. So, our love story began in a completely filmy (cinematic) and sweet way, with some ups and downs. We decided that if our parents agreed in the future, we would move forward together in life. And if they didn't agree, we would try our best to convince them. If our love develops to that extent, we are ready to face anything. So, we accepted it to some extent, and once again, thanks to our close best friends for their support.",
  "(24) Since the beginning of our relationship, conversations have played the most significant part, which has always been present between us. Through these conversations, we have been able to bridge any gaps between us. It involves providing satisfying and valid reasons, maintaining a positive mindset, not overthinking, and, if necessary, patiently explaining with love. We experience this every day, and neither of us has ever grown tired of it. We understand each other well, and we value breaks and personal space. Overall, our level of understanding each other is excellent and we are going to maintain it forever. I want to express my gratitude for your companionship, my dear.",
  "(25) So, yes, now I would like to talk about our first hug. One night, we were playing truth or dare through messages, and I dared you to hug me the next day. You accepted the dare. The following morning, as soon as you arrived, you gave me a side hug on the stairs. That was the first-ever hug I received, and even though it was simple and casual, it became special to me.I still remember the smile you had after that hug on that day when we were sitting together in lectures.",
  "(26) I remember everything, Kishu. you told me not to put my phone on airplane mode and turn it off while sleeping at night , I knew how much you cared for someone close to you. So, I stopped doing that from the very next night. And of course, I never kept my phone on silent until you reached college. Oh, I remember that day when your Activa ran out of petrol, and I couldn't help you because my phone was on silent. I saw you hurt for the first time because of me. But that incident led to our first ride together because the next time you needed to refill your petrol, we went together for the first time.",
  "(27) So, we have started to become a little more confident in each other. It goes beyond mere words, my friend. Seriously, no one can understand the depth of this relationship like we do, especially Kashish. I am truly, truly grateful for it. It was the beginning of February when I created a video after our Arham's class. In that video, I expressed my words confidently, stating that I will marry this girl, and I will replay it during our wedding. That day, I don't know how I gained such confidence. However, it's important to note that we don't want to boast about it.",
  "(28) Every day, we put in numerous small efforts to support and uplift each other because we understand that challenges and disagreements are a natural part of life. We have learned to embrace and accept whatever is required to navigate through them. However, we faced an additional obstacle where our friendship with our friends started to deteriorate at a profound level. Fortunately, we are slowly but surely rebuilding that connection. Our friends hold an incredibly special place in our hearts, don't they, Kashish? Moreover, we are gradually realizing that it's not a matter of you versus me, but rather a united front of us against the problems.",
  "(29) February was a wonderful month for both of us, where we started understanding each other on a deeper level. We learned about each other's flaws and strengths, explained ourselves to one another, and our love grew. During Valentine's Week, we exchanged chocolates and found different reasons to spend time alone, like going on rides together and studying together. It was also the time when Arham started preparing for entrance exams. I also remember the day when all of us, including Jayesh, Darshita, you, and I, went to the riverfront. We also went cycling there.",
  "(30) Now, what I am about to tell you is about our first movie, Jab We Met. The day was 28th February.That day was incredibly special for us. It was on that day that I kissed you for the first time. In the first half of the movie, I kissed your cheeks, forehead, and hands. I tried to kiss you on the lips, but we weren't sure. It was a thrilling and nerve-wracking experience because I didn't want to ruin that special day. However, I still remember it vividly. We were sitting in the last corner seat at the top in the PVR theater for the *Jab We Met* show. That day, you asked me why my nose was so cold, and in the midst of our emotions, I moved closer and jokingly asked if I could check your nose temperature against mine. It was such a romantic moment, and I can still feel it right now. You responded, Fine, come closer, and I asked, Are you sure? That's when we shared our first ever lip kiss, and it was the most special day ever.Apart from that, we have also accepted physical intimacy with the same level of respect as we continue to move forward in our lives. We have maintained our respect for each other, and this respect will always remain intact.From that day onwards, I considered myself as your boyfriend and you as my girlfriend.",
  "(31) Until now, there hasn't been a moment where we both said I love you to each other. But gradually, one day, we started expressing our feelings and saying love you. It was a day when I was crying due to my worries, and finally, you said those magical words, I love you, Jaymin. From that day onwards, we accepted that we can openly say those words to each other but actually when its needed.I can take long breaths and relive these moments again and again. I love you, Kashish Jain.",
  "(32) We are best friends to each other, and after every conflict and moment of anxiety, we have always taken the time to explain ourselves. I am thankful for that, Kashish.After the beginning of March, gradually everyone in college came to know that we are together. However, our relationship is no longer a secret; it is private.Both of our individual groups started accepting each other, and we enjoyed the Dhuleti festival, the festival of colors, together. It was our first festival as a bf-gf after starting our relationship.",
  "(33) Gradually, towards the end of March, everything was falling into place, and then our exams were about to begin. Throughout April, we were busy with exams, and we learned a lot. We worked hard, and you specifically learned how to grasp concepts effectively. Despite our busy schedules, we always made time for each other. If we talk about studies instead of our relationship, both of us have helped each other a lot. Whether it's maintaining my schedule, managing timetables, or self-development, in all those aspects where we were together, thank you very much, Kashish. I am ready to continue nurturing this relationship and be there for you throughout our lives, Kashish, my dear.",
  "(34) Exams have ended, and now the vacation has begun. We had a great time together at Jayesh's brother's wedding, but as the vacation started, the distance between us increased. We missed each other a lot, but we stayed connected online all the time. We continued learning together through Google Meet and stayed together virtually.We met during the vacation on May 10th to watch a movie, and it was an incredibly amazing day. It had been a long time since we had seen each other. After that, 21 days went by, and we spontaneously made a plan for you to skip the gym, and I would come to meet you. We had some coco together, and then, on the street, I kissed you, Kashish. It felt like a newly born love, it felt like our first kiss and it was such an exhilarating feeling.",
  "(35) June began, and gradually the days passed, and our anticipation came to an end. Our vacation came to a close, and you, Yashpal, Aarushi, and I had a delightful time together for the first time at an American eatery, enjoying donuts. It was such a nice day.The following day, college started, and on that very day, we met everyone. It was Xavier's birthday, and we celebrated it together. We also celebrated Kavya's birthday, and you joined the group celebration at Viraj's house. It was a very special day for me, Kashish, seriously. I even fell asleep in your lap that day. It was so comfortable and comforting.",
  "(36) Now we were in our final year of college, and since the beginning, a hectic routine had started. However, we were enjoying these days. Kashish, Darshita, and I formed a group of three for our Software Development Project (SDP), and we started working diligently. Kashish and I were particularly working with great dedication.During this time, I started planning for your birthday and even before the vacation ended, I had already begun working on this website from 6th June.I still feel a void that you couldn't join the trip to Imagica, and I am truly sorry for that, Kashish. But in the future, we will definitely go on a trip together. We will make sure to take permissions from home, and I missed you a lot during that time.",
  "(37) Today, as I write this, it is the 29th of June. Kashish, until now, we have shared so many special moments and have showered each other with love. However, I would like to remind you of our recent and most, most, most special moment. A couple of days ago, our college classes had ended, and it was raining outside. We found a corner in the college campus during the rain and shared kisses. It was an incredibly special moment, and I don't need to describe it further because you also know how special it was, Kashish, seriously.i love you Kashish jain",
  "(38) So, on the 30th of June, 2023, tomorrow, it's your birthday, Kashish. I have made plans for you, and I can't describe them right now, but they are going to be special for you. I hope you will like all the surprises and gifts I have prepared. I know that we are already gifts for each other, but I still want to express my love as much as I can.I pray to God that this bond remains strong forever. I am thankful to God, and I am thankful to you, Kashish. You are my world. After creating this story of our six months journey,  I am left speechless. How can I express my infinite feelings, Kashish? So, I am going to put a full stop in this website's story, but our journey has just begun. It's only the beginning, our lifestory until this day is just a spark that will turn into a blazing fire, it is just a drop of water that will become an ocean, just a small piece of air that will become essential oxygen for everyone, just a small part of dust that will transform into the Earth, just one cloud in the sky that will expand into the vastness of space. Our journey is infinite, and we will remain together, holding each other's hands. I feel tears welling up as I end this story. I love you, Kashish Jain.",
];

var currentParagraphIndex = 0;
var journeyParagraph = document.getElementById("journey");
var progressIndicator = document.getElementById("progressIndicator");

function showNext() {
  currentParagraphIndex++;
  if (currentParagraphIndex >= paragraphs.length) {
    currentParagraphIndex = 0;
  }
  journeyParagraph.textContent = paragraphs[currentParagraphIndex];
}

function showPrevious() {
  currentParagraphIndex--;
  if (currentParagraphIndex < 0) {
    currentParagraphIndex = paragraphs.length - 1;
  }
  journeyParagraph.textContent = paragraphs[currentParagraphIndex];
}
